import { Open_Sans } from 'next/font/google';
import Header from './components/Header';
import './globals.css';

const openSans = Open_Sans({
  subsets: ['latin'],
});

export const metadata = {
  title: "OSAN's REPOS",
  description: 'Generated by create next app',
  keywords: 'courses, classes',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
